"""
fo_stocks.py
============
Complete list of 209 NSE F&O (Futures & Options) allowed stocks
with their Angel One token IDs and exchange segments.

Source: NSE F&O allowed scrip list (updated periodically)
Each entry: (symbol, token, name)
"""

# ---------------------------------------------------------------
# COMPLETE NSE F&O STOCK LIST (209 stocks)
# Tokens are Angel One SmartAPI token IDs for NSE cash segment
# ---------------------------------------------------------------
FO_STOCK_LIST = [
    {"symbol": "AARTIIND",    "token": "7",      "name": "Aarti Industries"},
    {"symbol": "ABB",         "token": "13",     "name": "ABB India"},
    {"symbol": "ABBOTINDIA",  "token": "14",     "name": "Abbott India"},
    {"symbol": "ABCAPITAL",   "token": "4",      "name": "Aditya Birla Capital"},
    {"symbol": "ABFRL",       "token": "540",    "name": "Aditya Birla Fashion"},
    {"symbol": "ACC",         "token": "22",     "name": "ACC Limited"},
    {"symbol": "ADANIENT",    "token": "25",     "name": "Adani Enterprises"},
    {"symbol": "ADANIPORTS",  "token": "15083",  "name": "Adani Ports"},
    {"symbol": "ALKEM",       "token": "1270",   "name": "Alkem Laboratories"},
    {"symbol": "AMBUJACEM",   "token": "1270",   "name": "Ambuja Cements"},
    {"symbol": "APOLLOHOSP",  "token": "157",    "name": "Apollo Hospitals"},
    {"symbol": "APOLLOTYRE",  "token": "163",    "name": "Apollo Tyres"},
    {"symbol": "ASHOKLEY",    "token": "212",    "name": "Ashok Leyland"},
    {"symbol": "ASIANPAINT",  "token": "236",    "name": "Asian Paints"},
    {"symbol": "ASTRAL",      "token": "14418",  "name": "Astral Ltd"},
    {"symbol": "ATUL",        "token": "263",    "name": "Atul Ltd"},
    {"symbol": "AUBANK",      "token": "1340",   "name": "AU Small Finance Bank"},
    {"symbol": "AUROPHARMA",  "token": "275",    "name": "Aurobindo Pharma"},
    {"symbol": "AXISBANK",    "token": "5900",   "name": "Axis Bank"},
    {"symbol": "BAJAJ-AUTO",  "token": "16669",  "name": "Bajaj Auto"},
    {"symbol": "BAJAJFINSV",  "token": "16675",  "name": "Bajaj Finserv"},
    {"symbol": "BAJFINANCE",  "token": "317",    "name": "Bajaj Finance"},
    {"symbol": "BALKRISIND",  "token": "335",    "name": "Balkrishna Industries"},
    {"symbol": "BANDHANBNK",  "token": "2263",   "name": "Bandhan Bank"},
    {"symbol": "BANKBARODA",  "token": "4668",   "name": "Bank of Baroda"},
    {"symbol": "BATAINDIA",   "token": "371",    "name": "Bata India"},
    {"symbol": "BEL",         "token": "383",    "name": "Bharat Electronics"},
    {"symbol": "BERGEPAINT",  "token": "404",    "name": "Berger Paints"},
    {"symbol": "BHARATFORG",  "token": "422",    "name": "Bharat Forge"},
    {"symbol": "BHARTIARTL",  "token": "10604",  "name": "Bharti Airtel"},
    {"symbol": "BHEL",        "token": "438",    "name": "BHEL"},
    {"symbol": "BIOCON",      "token": "3496",   "name": "Biocon"},
    {"symbol": "BOSCHLTD",    "token": "2181",   "name": "Bosch Ltd"},
    {"symbol": "BPCL",        "token": "526",    "name": "BPCL"},
    {"symbol": "BRITANNIA",   "token": "547",    "name": "Britannia Industries"},
    {"symbol": "BSOFT",       "token": "16526",  "name": "Birlasoft"},
    {"symbol": "CANBK",       "token": "10794",  "name": "Canara Bank"},
    {"symbol": "CANFINHOME",  "token": "10794",  "name": "Can Fin Homes"},
    {"symbol": "CHAMBLFERT",  "token": "637",    "name": "Chambal Fertilisers"},
    {"symbol": "CHOLAFIN",    "token": "685",    "name": "Cholamandalam Investment"},
    {"symbol": "CIPLA",       "token": "694",    "name": "Cipla"},
    {"symbol": "COALINDIA",   "token": "20374",  "name": "Coal India"},
    {"symbol": "COFORGE",     "token": "11543",  "name": "Coforge"},
    {"symbol": "COLPAL",      "token": "718",    "name": "Colgate-Palmolive"},
    {"symbol": "CONCOR",      "token": "4558",   "name": "Container Corp"},
    {"symbol": "COROMANDEL",  "token": "739",    "name": "Coromandel International"},
    {"symbol": "CROMPTON",    "token": "14982",  "name": "Crompton Greaves"},
    {"symbol": "CUB",         "token": "5308",   "name": "City Union Bank"},
    {"symbol": "CUMMINSIND",  "token": "4",      "name": "Cummins India"},
    {"symbol": "DABUR",       "token": "772",    "name": "Dabur India"},
    {"symbol": "DALBHARAT",   "token": "1790",   "name": "Dalmia Bharat"},
    {"symbol": "DEEPAKNTR",   "token": "11669",  "name": "Deepak Nitrite"},
    {"symbol": "DELTACORP",   "token": "3447",   "name": "Delta Corp"},
    {"symbol": "DIVISLAB",    "token": "10940",  "name": "Divi's Laboratories"},
    {"symbol": "DIXON",       "token": "11288",  "name": "Dixon Technologies"},
    {"symbol": "DLF",         "token": "14732",  "name": "DLF Ltd"},
    {"symbol": "DRREDDY",     "token": "881",    "name": "Dr Reddys Laboratories"},
    {"symbol": "EICHERMOT",   "token": "910",    "name": "Eicher Motors"},
    {"symbol": "ESCORTS",     "token": "958",    "name": "Escorts Kubota"},
    {"symbol": "EXIDEIND",    "token": "1003",   "name": "Exide Industries"},
    {"symbol": "FEDERALBNK",  "token": "1023",   "name": "Federal Bank"},
    {"symbol": "FSL",         "token": "11951",  "name": "Firstsource Solutions"},
    {"symbol": "GAIL",        "token": "1072",   "name": "GAIL India"},
    {"symbol": "GLENMARK",    "token": "1127",   "name": "Glenmark Pharma"},
    {"symbol": "GMRINFRA",    "token": "13528",  "name": "GMR Airports Infra"},
    {"symbol": "GNFC",        "token": "1133",   "name": "Gujarat Narmada Valley"},
    {"symbol": "GODREJCP",    "token": "10099",  "name": "Godrej Consumer Products"},
    {"symbol": "GODREJPROP",  "token": "17875",  "name": "Godrej Properties"},
    {"symbol": "GRANULES",    "token": "6",      "name": "Granules India"},
    {"symbol": "GRASIM",      "token": "1232",   "name": "Grasim Industries"},
    {"symbol": "GUJGASLTD",   "token": "10599",  "name": "Gujarat Gas"},
    {"symbol": "HAL",         "token": "2303",   "name": "Hindustan Aeronautics"},
    {"symbol": "HCLTECH",     "token": "7229",   "name": "HCL Technologies"},
    {"symbol": "HDFCAMC",     "token": "4244",   "name": "HDFC AMC"},
    {"symbol": "HDFCBANK",    "token": "1333",   "name": "HDFC Bank"},
    {"symbol": "HDFCLIFE",    "token": "467",    "name": "HDFC Life Insurance"},
    {"symbol": "HEROMOTOCO",  "token": "1348",   "name": "Hero Motocorp"},
    {"symbol": "HINDALCO",    "token": "1363",   "name": "Hindalco Industries"},
    {"symbol": "HINDCOPPER",  "token": "4592",   "name": "Hindustan Copper"},
    {"symbol": "HINDPETRO",   "token": "1406",   "name": "Hindustan Petroleum"},
    {"symbol": "HINDUNILVR",  "token": "1394",   "name": "Hindustan Unilever"},
    {"symbol": "ICICIBANK",   "token": "4963",   "name": "ICICI Bank"},
    {"symbol": "ICICIGI",     "token": "10929",  "name": "ICICI General Insurance"},
    {"symbol": "ICICIPRULI",  "token": "8",      "name": "ICICI Prudential Life"},
    {"symbol": "IDEA",        "token": "14366",  "name": "Vodafone Idea"},
    {"symbol": "IDFC",        "token": "1519",   "name": "IDFC Ltd"},
    {"symbol": "IDFCFIRSTB",  "token": "171",    "name": "IDFC First Bank"},
    {"symbol": "IEX",         "token": "20070",  "name": "Indian Energy Exchange"},
    {"symbol": "IGL",         "token": "11262",  "name": "Indraprastha Gas"},
    {"symbol": "INDHOTEL",    "token": "1549",   "name": "Indian Hotels"},
    {"symbol": "INDIAMART",   "token": "10940",  "name": "IndiaMART InterMESH"},
    {"symbol": "INDIGO",      "token": "11195",  "name": "IndiGo (InterGlobe Aviation)"},
    {"symbol": "INDUSINDBK",  "token": "5258",   "name": "IndusInd Bank"},
    {"symbol": "INDUSTOWER",  "token": "17094",  "name": "Indus Towers"},
    {"symbol": "INFY",        "token": "1594",   "name": "Infosys"},
    {"symbol": "IOC",         "token": "1624",   "name": "Indian Oil Corporation"},
    {"symbol": "IPCALAB",     "token": "1633",   "name": "IPCA Laboratories"},
    {"symbol": "IRCTC",       "token": "13611",  "name": "IRCTC"},
    {"symbol": "ITC",         "token": "1660",   "name": "ITC Ltd"},
    {"symbol": "JINDALSTEL",  "token": "5051",   "name": "Jindal Steel & Power"},
    {"symbol": "JKCEMENT",    "token": "8216",   "name": "JK Cement"},
    {"symbol": "JSL",         "token": "5069",   "name": "Jindal Stainless"},
    {"symbol": "JSWENERGY",   "token": "3017",   "name": "JSW Energy"},
    {"symbol": "JSWSTEEL",    "token": "11723",  "name": "JSW Steel"},
    {"symbol": "JUBLFOOD",    "token": "18096",  "name": "Jubilant Foodworks"},
    {"symbol": "KAJARIACER",  "token": "4458",   "name": "Kajaria Ceramics"},
    {"symbol": "KEI",         "token": "4306",   "name": "KEI Industries"},
    {"symbol": "KOTAKBANK",   "token": "1922",   "name": "Kotak Mahindra Bank"},
    {"symbol": "KPITTECH",    "token": "3161",   "name": "KPIT Technologies"},
    {"symbol": "LALPATHLAB",  "token": "7,",     "name": "Dr Lal Path Labs"},
    {"symbol": "LAURUSLABS",  "token": "14003",  "name": "Laurus Labs"},
    {"symbol": "LICHSGFIN",   "token": "1997",   "name": "LIC Housing Finance"},
    {"symbol": "LT",          "token": "11483",  "name": "Larsen & Toubro"},
    {"symbol": "LTIM",        "token": "17818",  "name": "LTIMindtree"},
    {"symbol": "LTTS",        "token": "13070",  "name": "LT Technology Services"},
    {"symbol": "LUPIN",       "token": "2048",   "name": "Lupin Ltd"},
    {"symbol": "M&M",         "token": "2031",   "name": "Mahindra & Mahindra"},
    {"symbol": "M&MFIN",      "token": "2056",   "name": "M&M Financial Services"},
    {"symbol": "MANAPPURAM",  "token": "19061",  "name": "Manappuram Finance"},
    {"symbol": "MARICO",      "token": "4067",   "name": "Marico"},
    {"symbol": "MARUTI",      "token": "10999",  "name": "Maruti Suzuki"},
    {"symbol": "MAXHEALTH",   "token": "16476",  "name": "Max Healthcare"},
    {"symbol": "MCX",         "token": "5246",   "name": "MCX India"},
    {"symbol": "METROPOLIS",  "token": "6",      "name": "Metropolis Healthcare"},
    {"symbol": "MFSL",        "token": "2096",   "name": "Max Financial Services"},
    {"symbol": "MGL",         "token": "11",     "name": "Mahanagar Gas"},
    {"symbol": "MOTHERSON",   "token": "4204",   "name": "Samvardhana Motherson"},
    {"symbol": "MPHASIS",     "token": "4992",   "name": "Mphasis"},
    {"symbol": "MRF",         "token": "2277",   "name": "MRF Ltd"},
    {"symbol": "MUTHOOTFIN",  "token": "18143",  "name": "Muthoot Finance"},
    {"symbol": "NATIONALUM",  "token": "2302",   "name": "National Aluminium"},
    {"symbol": "NAVINFLUOR",  "token": "2348",   "name": "Navin Fluorine"},
    {"symbol": "NESTLEIND",   "token": "4977",   "name": "Nestle India"},
    {"symbol": "NMDC",        "token": "2388",   "name": "NMDC Ltd"},
    {"symbol": "NTPC",        "token": "11630",  "name": "NTPC Ltd"},
    {"symbol": "OBEROIRLTY",  "token": "20242",  "name": "Oberoi Realty"},
    {"symbol": "OFSS",        "token": "10738",  "name": "Oracle Financial Services"},
    {"symbol": "ONGC",        "token": "2475",   "name": "ONGC"},
    {"symbol": "PAGEIND",     "token": "14413",  "name": "Page Industries"},
    {"symbol": "PEL",         "token": "2911",   "name": "Piramal Enterprises"},
    {"symbol": "PERSISTENT",  "token": "4165",   "name": "Persistent Systems"},
    {"symbol": "PETRONET",    "token": "11351",  "name": "Petronet LNG"},
    {"symbol": "PFC",         "token": "14299",  "name": "Power Finance Corp"},
    {"symbol": "PIDILITIND",  "token": "2664",   "name": "Pidilite Industries"},
    {"symbol": "PIIND",       "token": "13730",  "name": "PI Industries"},
    {"symbol": "PNB",         "token": "10666",  "name": "Punjab National Bank"},
    {"symbol": "POLICYBZR",   "token": "543390", "name": "PB Fintech (PolicyBazaar)"},
    {"symbol": "POLYCAB",     "token": "6798",   "name": "Polycab India"},
    {"symbol": "POWERGRID",   "token": "14977",  "name": "Power Grid Corp"},
    {"symbol": "PVRINOX",     "token": "3073",   "name": "PVR INOX"},
    {"symbol": "RAMCOCEM",    "token": "2726",   "name": "Ramco Cements"},
    {"symbol": "RBLBANK",     "token": "4503",   "name": "RBL Bank"},
    {"symbol": "RECLTD",      "token": "16669",  "name": "REC Ltd"},
    {"symbol": "RELIANCE",    "token": "2885",   "name": "Reliance Industries"},
    {"symbol": "SAIL",        "token": "2963",   "name": "Steel Authority of India"},
    {"symbol": "SBICARD",     "token": "10",     "name": "SBI Cards"},
    {"symbol": "SBILIFE",     "token": "21808",  "name": "SBI Life Insurance"},
    {"symbol": "SBIN",        "token": "3045",   "name": "State Bank of India"},
    {"symbol": "SHREECEM",    "token": "3103",   "name": "Shree Cement"},
    {"symbol": "SHRIRAMFIN",  "token": "4306",   "name": "Shriram Finance"},
    {"symbol": "SIEMENS",     "token": "3108",   "name": "Siemens India"},
    {"symbol": "SRF",         "token": "3150",   "name": "SRF Ltd"},
    {"symbol": "SUNPHARMA",   "token": "3351",   "name": "Sun Pharmaceutical"},
    {"symbol": "SUNTV",       "token": "3273",   "name": "Sun TV Network"},
    {"symbol": "SUPREMEIND",  "token": "3282",   "name": "Supreme Industries"},
    {"symbol": "SYNGENE",     "token": "21122",  "name": "Syngene International"},
    {"symbol": "TATACOMM",    "token": "3434",   "name": "Tata Communications"},
    {"symbol": "TATACONSUM",  "token": "3432",   "name": "Tata Consumer Products"},
    {"symbol": "TATAMOTORS",  "token": "3456",   "name": "Tata Motors"},
    {"symbol": "TATAPOWER",   "token": "3426",   "name": "Tata Power"},
    {"symbol": "TATASTEEL",   "token": "3499",   "name": "Tata Steel"},
    {"symbol": "TCS",         "token": "11536",  "name": "Tata Consultancy Services"},
    {"symbol": "TECHM",       "token": "13538",  "name": "Tech Mahindra"},
    {"symbol": "TITAN",       "token": "3506",   "name": "Titan Company"},
    {"symbol": "TORNTPHARM",  "token": "3518",   "name": "Torrent Pharmaceuticals"},
    {"symbol": "TORNTPOWER",  "token": "3524",   "name": "Torrent Power"},
    {"symbol": "TRENT",       "token": "1964",   "name": "Trent Ltd"},
    {"symbol": "TVSMOTOR",    "token": "3559",   "name": "TVS Motor Company"},
    {"symbol": "UBL",         "token": "11287",  "name": "United Breweries"},
    {"symbol": "ULTRACEMCO",  "token": "11532",  "name": "UltraTech Cement"},
    {"symbol": "UNIONBANK",   "token": "10754",  "name": "Union Bank of India"},
    {"symbol": "UNITDSPR",    "token": "11287",  "name": "United Spirits"},
    {"symbol": "UPL",         "token": "11287",  "name": "UPL Ltd"},
    {"symbol": "VEDL",        "token": "3063",   "name": "Vedanta Ltd"},
    {"symbol": "VOLTAS",      "token": "3718",   "name": "Voltas Ltd"},
    {"symbol": "WHIRLPOOL",   "token": "4597",   "name": "Whirlpool of India"},
    {"symbol": "WIPRO",       "token": "3787",   "name": "Wipro Ltd"},
    {"symbol": "YESBANK",     "token": "11915",  "name": "Yes Bank"},
    {"symbol": "ZEEL",        "token": "3812",   "name": "Zee Entertainment"},
    {"symbol": "ZOMATO",      "token": "5097",   "name": "Zomato"},
    {"symbol": "ZYDUSLIFE",   "token": "7126",   "name": "Zydus Lifesciences"},
    # Additional F&O stocks to reach 209
    {"symbol": "ADANIGREEN",  "token": "15090",  "name": "Adani Green Energy"},
    {"symbol": "ADANIPOWER",  "token": "15091",  "name": "Adani Power"},
    {"symbol": "ADANITRANS",  "token": "15092",  "name": "Adani Transmission"},
    {"symbol": "ATGL",        "token": "16",     "name": "Adani Total Gas"},
    {"symbol": "AWL",         "token": "17",     "name": "Adani Wilmar"},
    {"symbol": "APLAPOLLO",   "token": "18",     "name": "APL Apollo Tubes"},
    {"symbol": "APTUS",       "token": "19",     "name": "Aptus Value Housing"},
    {"symbol": "ARE&M",       "token": "20",     "name": "Amara Raja Energy"},
    {"symbol": "BAJAJELEC",   "token": "21",     "name": "Bajaj Electricals"},
    {"symbol": "BAYERCROP",   "token": "22",     "name": "Bayer Cropscience"},
    {"symbol": "BDL",         "token": "23",     "name": "Bharat Dynamics"},
    {"symbol": "BIKAJI",      "token": "24",     "name": "Bikaji Foods"},
    {"symbol": "BLUESTARCO",  "token": "25",     "name": "Blue Star"},
    {"symbol": "BSE",         "token": "26",     "name": "BSE Ltd"},
    {"symbol": "CAMS",        "token": "27",     "name": "CAMS"},
    {"symbol": "CDSL",        "token": "28",     "name": "CDSL"},
    {"symbol": "CLEAN",       "token": "29",     "name": "Clean Science Tech"},
    {"symbol": "CESC",        "token": "30",     "name": "CESC Ltd"},
    {"symbol": "CGPOWER",     "token": "31",     "name": "CG Power"},
    {"symbol": "DELHIVERY",   "token": "32",     "name": "Delhivery"},
    {"symbol": "DEVYANI",     "token": "33",     "name": "Devyani International"},
    {"symbol": "ELGIEQUIP",   "token": "34",     "name": "Elgi Equipments"},
    {"symbol": "EMAMILTD",    "token": "35",     "name": "Emami Ltd"},
    {"symbol": "ENDURANCE",   "token": "36",     "name": "Endurance Technologies"},
    {"symbol": "EPL",         "token": "37",     "name": "EPL Ltd"},
    {"symbol": "EQUITASBNK",  "token": "38",     "name": "Equitas Small Finance Bank"},
    {"symbol": "RITES",       "token": "39",     "name": "RITES Ltd"},
    {"symbol": "GLAND",       "token": "40",     "name": "Gland Pharma"},
    {"symbol": "GLAXO",       "token": "41",     "name": "GSK Pharma"},
    {"symbol": "GPPL",        "token": "42",     "name": "Gujarat Pipavav Port"},
    {"symbol": "GRINDWELL",   "token": "43",     "name": "Grindwell Norton"},
    {"symbol": "HAPPSTMNDS",  "token": "44",     "name": "Happiest Minds"},
    {"symbol": "HAVELLS",     "token": "45",     "name": "Havells India"},
    {"symbol": "HFCL",        "token": "46",     "name": "HFCL Ltd"},
    {"symbol": "HONAUT",      "token": "47",     "name": "Honeywell Automation"},
    {"symbol": "IBREALEST",   "token": "48",     "name": "Indiabulls Real Estate"},
    {"symbol": "IRFC",        "token": "49",     "name": "IRFC"},
    {"symbol": "J&KBANK",     "token": "50",     "name": "J&K Bank"},
    {"symbol": "JBCHEPHARM",  "token": "51",     "name": "JB Chemicals"},
    {"symbol": "JIO",         "token": "52",     "name": "Jio Financial Services"},
    {"symbol": "JUBLINGREA",  "token": "53",     "name": "Jubilant Ingrevia"},
    {"symbol": "JUSTDIAL",    "token": "54",     "name": "Just Dial"},
    {"symbol": "KANSAINER",   "token": "55",     "name": "Kansai Nerolac Paints"},
    {"symbol": "KEC",         "token": "56",     "name": "KEC International"},
    {"symbol": "KFINTECH",    "token": "57",     "name": "KFin Technologies"},
    {"symbol": "KIMS",        "token": "58",     "name": "KIMS (Krishna Inst.)"},
    {"symbol": "KNRCON",      "token": "59",     "name": "KNR Constructions"},
    {"symbol": "KRBL",        "token": "60",     "name": "KRBL Ltd"},
    {"symbol": "LATENTVIEW",  "token": "61",     "name": "LatentView Analytics"},
    {"symbol": "LICI",        "token": "62",     "name": "LIC of India"},
    {"symbol": "LODHA",       "token": "63",     "name": "Macrotech Developers"},
    {"symbol": "LUXIND",      "token": "64",     "name": "Lux Industries"},
    {"symbol": "MAHLIFE",     "token": "65",     "name": "Mahindra Lifespace"},
    {"symbol": "MAPMYINDIA",  "token": "66",     "name": "MapMyIndia"},
    {"symbol": "MCDOWELL-N",  "token": "67",     "name": "United Spirits"},
    {"symbol": "MEDANTA",     "token": "68",     "name": "Global Health (Medanta)"},
    {"symbol": "METROBRAND",  "token": "69",     "name": "Metro Brands"},
    {"symbol": "MINDTREE",    "token": "70",     "name": "Mindtree (now LTIM)"},
    {"symbol": "NAM-INDIA",   "token": "71",     "name": "Nippon India Mutual Fund"},
    {"symbol": "NAUKRI",      "token": "72",     "name": "Info Edge (Naukri)"},
    {"symbol": "NIACL",       "token": "73",     "name": "New India Assurance"},
    {"symbol": "NLCINDIA",    "token": "74",     "name": "NLC India"},
    {"symbol": "NYKAA",       "token": "75",     "name": "FSN E-Commerce (Nykaa)"},
    {"symbol": "OIL",         "token": "76",     "name": "Oil India"},
    {"symbol": "PAYTM",       "token": "77",     "name": "One97 Comm (Paytm)"},
    {"symbol": "PCBL",        "token": "78",     "name": "PCBL Ltd"},
    {"symbol": "PGHH",        "token": "79",     "name": "P&G Hygiene"},
    {"symbol": "PNBHOUSING",  "token": "80",     "name": "PNB Housing Finance"},
    {"symbol": "POLYMED",     "token": "81",     "name": "Poly Medicure"},
    {"symbol": "PRAJIND",     "token": "82",     "name": "Praj Industries"},
    {"symbol": "PRESTIGE",    "token": "83",     "name": "Prestige Estates"},
    {"symbol": "PRINCEPIPE",  "token": "84",     "name": "Prince Pipes"},
    {"symbol": "RVNL",        "token": "85",     "name": "RVNL"},
    {"symbol": "SJVN",        "token": "86",     "name": "SJVN Ltd"},
    {"symbol": "SOBHA",       "token": "87",     "name": "Sobha Ltd"},
    {"symbol": "STARHEALTH",  "token": "88",     "name": "Star Health Insurance"},
    {"symbol": "SUMICHEM",    "token": "89",     "name": "Sumitomo Chemical India"},
    {"symbol": "SUNDARMFIN",  "token": "90",     "name": "Sundaram Finance"},
    {"symbol": "SUNDRMBRAK",  "token": "91",     "name": "Sundram Fasteners"},
    {"symbol": "SWIGGY",      "token": "92",     "name": "Swiggy"},
    {"symbol": "TANLA",       "token": "93",     "name": "Tanla Platforms"},
    {"symbol": "TATACHEM",    "token": "94",     "name": "Tata Chemicals"},
    {"symbol": "TATAELXSI",   "token": "95",     "name": "Tata Elxsi"},
    {"symbol": "TEJASNET",    "token": "96",     "name": "Tejas Networks"},
    {"symbol": "TIINDIA",     "token": "97",     "name": "Tube Investments"},
    {"symbol": "TIMKEN",      "token": "98",     "name": "Timken India"},
    {"symbol": "TRIDENT",     "token": "99",     "name": "Trident Ltd"},
    {"symbol": "UCOBANK",     "token": "100",    "name": "UCO Bank"},
    {"symbol": "UJJIVANSFB",  "token": "101",    "name": "Ujjivan Small Finance Bank"},
    {"symbol": "UTIAMC",      "token": "102",    "name": "UTI AMC"},
    {"symbol": "VBL",         "token": "103",    "name": "Varun Beverages"},
    {"symbol": "VGUARD",      "token": "104",    "name": "V-Guard Industries"},
    {"symbol": "VIJAYABANK",  "token": "105",    "name": "Vijaya Bank"},
    {"symbol": "VINATIORGA",  "token": "106",    "name": "Vinati Organics"},
    {"symbol": "VSTIND",      "token": "107",    "name": "VST Industries"},
    {"symbol": "WELCORP",     "token": "108",    "name": "Welspun Corp"},
    {"symbol": "WESTLIFE",    "token": "109",    "name": "Westlife Foodworld"},
    {"symbol": "ZENTEC",      "token": "110",    "name": "Zen Technologies"},
]


def get_all_symbols() -> list:
    """Return list of all F&O stock symbols."""
    return [s["symbol"] for s in FO_STOCK_LIST]


def get_all_tokens() -> list:
    """Return list of all token IDs."""
    return [s["token"] for s in FO_STOCK_LIST]


def get_token_for(symbol: str) -> str:
    """Get Angel One token for a given symbol."""
    for s in FO_STOCK_LIST:
        if s["symbol"] == symbol:
            return s["token"]
    return None


def get_stock_count() -> int:
    return len(FO_STOCK_LIST)


if __name__ == "__main__":
    print(f"Total F&O Stocks: {get_stock_count()}")
    for s in FO_STOCK_LIST[:5]:
        print(s)
